### ISSUE TITLE
Bring CD image deployment configuration to main branch

### ISSUE THREAD

**Issue by davenquinn** [UW-Macrostrat/web#100]
@CannonLock, I see you've set up CD on your tracking branch. This is great, but there's now an inconsistent setup between that and the main branch.

This config should be broken out into a PR that addresses #89, and ideally #97, that can be applied directly to the main branch.

In general changes should be small-ish PRs focused on a single issue, rather than maintaining a separate tracking branch.

**Comment by CannonLock** [comment]
#102 adds a build test that will handle several of the proposed checks.
