### ISSUE TITLE
Implement Redux Store for Edit Interface

### ISSUE THREAD

**Issue by CannonLock** [UW-Macrostrat/web#108]
Need a way to be able to save the current state between reloads and allow the editors to select personal defaults.

**Comment by davenquinn** [comment]
We should discuss before you go down this path what you're hoping to achieve with Redux specifically. I'd rather get through the basic editing workflow before we worry too much about state persistence, customizability, and the like.

**Comment by davenquinn** [comment]
State management is important, but redux is not the way to do it.
