### ISSUE TITLE
Create centralized documentation page

### ISSUE THREAD

**Issue by davenquinn** [UW-Macrostrat/web#161]
Documentation is scattered in a few places. To start, we need a page that

- Links to all API documentation (e.g. Swagger, API specs, etc.)
- Links to any documentation of specific tools (e.g., map interface, ingestion web form)

**Comment by davenquinn** [comment]
This needs to be in place in the next few weeks. We can put it under the `/docs` route

**Comment by davenquinn** [comment]
See also #109, which contains broader documentation needs but is a bit more oriented towards the longer term.

**Comment by CannonLock** [comment]
Closed by #167
