### ISSUE TITLE
Strat name filter using hierarchy

### ISSUE THREAD

**Issue by cambro** [UW-Macrostrat/web#23]
https://dev.macrostrat.org/web-v3/#/z=8.8/x=-109.7874/y=38.4337/bedrock/columns/strat_name_concepts=8366

This map has several problems. First, the link doesn't seem to work (i.e., won't load when link copied and opened in browser).

https://dev.macrostrat.org/web-v3/#/z=8.9/x=-109.1263/y=38.5639/
Go here and filter "Glen Canyon" stratigraphic name. Then zoom in a bit. Some of the polygons (purple) disappear but they are from the same source (medium). 

Glen Canyon is a concept that includes the Navajo Formation, but that unit is not also plotted here. A group should include the children so all of the Glen Canyon children that are in this map view should be shown. It's also not clear why for the purple polygons the Glen Canyon Gp. is not listed as listed as a linked entity in Macrostrat linked data.

**Comment by cambro** [comment]
Still not clear on the strat_name filter and whether it is working or not. Example:
https://macrostrat.org/map/#/z=7.8/x=137.2756/y=-31.0286/bedrock/lines/
Simmens Quartzite is a strat_name in the map and can be filtered but filtering on this name shows no results in this area. @jczaplew

**Comment by cambro** [comment]
Clearly strat_name filtering isn't working at all, even when matched to Macrostrawt units, right now for some reason...
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/6107153/49186894-752fa480-f32b-11e8-9486-f016c9cafe95.png">

**Comment by Idzikowski-Casey** [comment]
It looks like these issues have been resolved in newer versions of the map. Although this issue brings up a good point about strat_name polygons not being rendered if the zoom level is too high. Perhaps if a strat_name_filter is applied the associated polygon should be rendered regardless of zoom level. I will make a new issue for this.
