### ISSUE TITLE
PBDB lithology='sedimentary' returns no results because filter shouldn't be used

### ISSUE THREAD

**Issue by cambro** [UW-Macrostrat/web#31]
PBDB has no "class" concept for lithology. They are all sedimentary. Thus, web-v3 should omit lithology filter for PBDB when lithology filter == 'sedimentary'

**Comment by Idzikowski-Casey** [comment]
I forgot to mention this issue in a commit message, but it's been closed for awhile. We currently have just disabled the `lithology` filter for PBDB. Currently the endpoint is returning a `500`status_code when the lithology filter is being used.

https://paleobiodb.org/data1.2/colls/summary.json?lithology=limestone&level=2
