### ISSUE TITLE
Column API call/query not working after age filter applied

### ISSUE THREAD

**Issue by cambro** [UW-Macrostrat/web#33]
To reproduce:

Turn on columns.
Filter by age.
Click on column.
No column data returned.

Remove filter by age.
Click on column.
Column data returned.

**Comment by Idzikowski-Casey** [comment]
I've found the source of this and corrected it. The map `onClick` was only querying the `column-fill` layer, however, when filters are applied the visible column layer has id `filtered-column-fill`. This issue will automatically close when the changes are merged to `main`.
