### ISSUE TITLE
Continual reloading of PBDB layers

### ISSUE THREAD

**Issue by davenquinn** [UW-Macrostrat/web#43]
Our recent updates to get the PBDB layers to always show has resulted in us continuously refreshing PBDB results. This has the consequence of hitting the PBDB API over and over again whenever the fossil layer is loaded. Visually, this manifests as the new loading spinner continually reactivating when the fossil layer is on.

This is not acceptable as it will stress PBDB servers when deployed. @Idzikowski-Casey can you fix?

**Comment by Idzikowski-Casey** [comment]
Certain PBDB layers are only visible at certain zoom levels, but in the `setMapyStyle` function each layer was being set to visible if `mapHasFossils`, which triggered a PBDB api call in `refreshPBDB`. However, inside this function, the pbdb layers are already being set to visible or not based on zoom. The conflicting visibility set inside `refreshPBDB` and what `setMapStyle` thinks should be the visibility was creating an endless loop. For now, I've changed `setMapStyle` to only call `refreshPBDB`. The main changes were in [this](https://github.com/UW-Macrostrat/web/commit/335dedfb25be4f5105301614171235a3fdec344f#diff-163477d46608ddbdf5fd49404e62ead4b7009520cac06251b125e3eda2ca089b) commit. 

This is an unsatisfying solution; however, as we parse out the `refreshPBDB` I think the organization will become more clear.
