### ISSUE TITLE
Add column view

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/web#5]
Add columns as an optional layer

**Comment by cambro** [comment]
Key here will be to develop a sweet renderer for the columns. Maybe we can get input on this from Daven if/when he comes.

**Comment by jczaplew** [comment]
Spatial layer has been added

**Comment by cambro** [comment]
Need to provide a bit more detail in the column summary (i.e., include col_group and col_name, show col_id in small text someplace for convenience in dev.) @jczaplew

**Comment by davenquinn** [comment]
Column details have been added, finally!
