### ISSUE TITLE
Make journals collapsible/expandable

### ISSUE THREAD

**Issue by aazaff** [UW-Macrostrat/web#52]
You can expand and collapse the Primary Literature from GeoDeepDive panel. When expanded this gives a list of articles grouped by journal. The length of results is potentially overwhelming. It would be great to be able to collapse all articles within an unwanted journal.

![image](https://user-images.githubusercontent.com/10422595/147794756-65ab5efd-3657-4459-9648-426749fa1a4c.png)

**Comment by davenquinn** [comment]
Yeah, agreed, this would be a nice feature.
