### ISSUE TITLE
Your Location

### ISSUE THREAD

**Issue by Idzikowski-Casey** [UW-Macrostrat/web#64]
Your location appears permanently greyed out in the layers menu.

**Comment by Idzikowski-Casey** [comment]
Looked into the Your Location button issue. There's a pretty basic Javascript API [navigator.geolocation](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/geolocation), that gets permission from the browser. I was able to get a callback to update the URI, but the map component viewport doesn't get updated on URI change. 

This may take some more state changes.

**Comment by davenquinn** [comment]
Here's a link to Mapbox's first-party geolocation control, which shows how to set this up on the map: https://github.com/mapbox/mapbox-gl-js/blob/f34b72f1927b51d8dbd929352bfaede25c509d69/src/ui/control/geolocate_control.js
