### ISSUE TITLE
fossil points don't render in far northern hemisphere

### ISSUE THREAD

**Issue by cambro** [UW-Macrostrat/web#68]
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/6107153/176883749-8c83bfe5-5b78-48e0-9c2d-1dcc3f6e231e.png">

**Comment by davenquinn** [comment]
This is an upstream issue with the Mapbox GL globe that we have successfully worked around for now:

  - https://docs.mapbox.com/mapbox-gl-js/guides/globe/#limitations-of-globe
  - https://github.com/mapbox/mapbox-gl-js/issues/11795
