### ISSUE TITLE
Link to coordinates and info panel

### ISSUE THREAD

**Issue by kueda** [UW-Macrostrat/web#74]
(Repost of https://github.com/UW-Macrostrat/burwell-app/issues/49 since this seems like the active repo now)

Right now you can link to coordinates like https://macrostrat.org/map/#x=-107.035&y=36.073&z=13.7, but it would be extra useful to link to coordinates and show the info panel for those coordinates showing all the overlapping units. IMO that should be the default behavior, but something like https://macrostrat.org/map/infopanel#x=-107.035&y=36.073&z=13.7 would be ok too.

FWIW, what I really want to do is provide a link from iNaturalist observation pages (like [this](https://www.inaturalist.org/observations/144195604)) to Macrostrat so iNat users can see the location of an biological observation in geological context, but the inability to link to a page that shows that info means such a link would be quite confusing in its current state.

**Comment by davenquinn** [comment]
Thanks for the report! I agree with this issue. I've actually been working on improving routing along those lines recently, alongside getting stratigraphic columns into the web app. I will keep you posted as how that is going, and once it gets a bit further, some options on where an initial link from iNaturalist could land.

**Comment by davenquinn** [comment]
This is now live. Links into Macrostrat now take the form `https://macrostrat.org/map/loc/<lon>/<lat>#z=<zoom>`. Hash parameters are optional but can specify alternate viewpoints and camera angles.

**Comment by kueda** [comment]
Awesome, thank you, @davenquinn. There's now a link to Macrostrat in the "Details" popover below the map on iNaturalist too, as of https://github.com/inaturalist/inaturalist/commit/71a38a76efebb5e5411cef2d954fac4af0264b96.

Related question: where's the best place to send people if they have issues / suggestions for what to show on the Macrostrat map? E.g. it seems like the infowindow shows coarser data than the map does (https://macrostrat.org/map/loc/-121.9458/37.8856#z=14.3 and https://macrostrat.org/map/loc/-121.9438/37.8834#z=14.3 are mapped differently but the infowindow says "Name: Franciscan Complex, unit 1 (Coast Ranges)" for both.

**Comment by davenquinn** [comment]
@kueda, for now, directing folks to create an issue in this Github repository is ideal. We're working on a new system for data-side feedback but that will take a bit to land. 

The issue you highlighted is a dumb bug that I'm working to fix now.

**Comment by kueda** [comment]
Great. FWIW, iNat folks are into this: https://forum.inaturalist.org/t/you-can-now-access-elevation-and-other-details-from-macrostrat-for-an-observations-location/39066
