### ISSUE TITLE
Put a page behind Auth

### ISSUE THREAD

**Issue by CannonLock** [UW-Macrostrat/web#96]
On the server side page: 

If they have a cookie: 

- Check if they are already logged in by hitting the {ingest_api}/security/me page to get the contents of the JWT. Check they have the correct groups to see this page. 

- Report if they aren't allowed, allow them if they are.

If they don't have a cookie: 

- Run a redirect page to the {ingest_api}/security/login with the url param {return_url: "<current page user is trying to reach>"}

- User will be taken to Identity provider. 

- On login they will be returned to the server page with the new cookie

**Comment by davenquinn** [comment]
Can we trust the cookie's grants in some cases? E.g. if they already have a short-dated access cookie, rather than a "refresh" cookie? Or should we always check?

**Comment by davenquinn** [comment]
Not checking would allow the page to also be rendered on the client side

**Comment by davenquinn** [comment]
@CannonLock I'd like this to get a high priority in its most basic form... some page, any page, behind auth. I feel like I need to see this in practice to start getting my head around how to work with it.

**Comment by CannonLock** [comment]
@davenquinn I had this completed at the time of issue creation. I opened this issue for discussion. 

Let me get my test instance in a place to show you at todays meeting.

**Comment by davenquinn** [comment]
OK sounds good. Broadly, though, this is definitely an "if a tree falls in the forest..." type thing. I'd like features like these to be linked to a pull request quickly. And while having them running on the test instance is good, that should at least be described in the issue. And I would want to see the changes merged to development or another more widely used instance early as well.

**Comment by CannonLock** [comment]
Closed by #102
